apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: us-central1-docker.pkg.dev/powerful-unison-413810/batch10/api-server:latest
      imagePullSecrets:
      - name: gcr-io

---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  selector:
    app: api-server
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer